name: Build and Test React Application

# Controls when the action will run.
on:
 # Triggers the workflow on push or pull request events but only for the main branch
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]
   
jobs:
  build_test:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest
